// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gofiber/fiber/v2"
	"github.com/wahyusahajaa/mulo-api-go/app/config"
	"github.com/wahyusahajaa/mulo-api-go/app/handlers"
	"github.com/wahyusahajaa/mulo-api-go/app/routers"
)

// Injectors from wire.go:

func InitializedApp() (*AppContainer, error) {
	handlersHandlers := handlers.NewHandlers()
	app := routers.ProviderFiberApp(handlersHandlers)
	configConfig := config.NewConfig()
	appContainer := &AppContainer{
		App:    app,
		Config: configConfig,
	}
	return appContainer, nil
}

// wire.go:

type AppContainer struct {
	App    *fiber.App
	Config *config.Config
}
