# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd"
bin = "tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "env", "development"]
log = "build.log"

[log]
time = true