services:
  app:
    container_name: mulo-api-prod
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    env_file:
      - .env.production
    restart: always
    expose:
      - "8080"
    volumes:
      - ./nginx/certs/postgresql-ca.pem:/certs/postgresql-ca.pem:ro
    networks:
      - mulo-shared-net

networks:
  mulo-shared-net:
    external: true
