version: '3.9'
services:
  nginx:
    container_name: mulo-api-nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx/conf/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/selfsigned.crt:/etc/nginx/certs/selfsigned.crt:ro
      - ./nginx/certs/selfsigned.key:/etc/nginx/certs/selfsigned.key:ro
    depends_on:
      - app
    networks:
      - mulo-api-dev
  app:
    container_name: mulo-api-dev
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8080:8080
    env_file:
      - .env.development
    restart: unless-stopped
    networks:
      - mulo-api-dev
    volumes:
      - .:/app                                # bind mounts
      - go-pkg:/go/pkg                        # module cache
      - go-build:/root/.cache/go-build        # Build cache
    depends_on:
      - db
  db:
    container_name: mulo-db-dev
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tungtungsahur}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-tralalelotralalala}
      POSTGRES_DB: ${POSTGRES_DB:-mulo_bombardino}
    volumes:
      - app-data:/var/lib/postgresql/data  # mount postgres data
    networks:
    - mulo-api-dev
    ports:
      - 5433:5432

volumes:
  go-pkg:       # for downloaded modules
  go-build:     # For compilation results
  app-data:     # For mouting postgres data

networks:
  mulo-api-dev:
    driver: bridge