version: '3.9'
services:
  app:
    container_name: mulo-api-prod
    build: 
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - ${APP_PORT:-8080}:8080
    env_file:
      - .env.${APP_ENV}
    restart: always
    networks:
      - mulo-api-prod

networks:
  mulo-api-prod:
    driver: bridge