version: "3.9"
services:
  nginx:
    container_name: mulo-api-nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx/conf/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/selfsigned.crt:/etc/nginx/certs/selfsigned.crt:ro
      - ./nginx/certs/selfsigned.key:/etc/nginx/certs/selfsigned.key:ro
    depends_on:
      - app
    networks:
      - mulo-shared-net
  app:
    container_name: mulo-api-prod
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - 8080:8080
    env_file:
      - .env.production
    restart: always
    volumes:
      - ./nginx/certs/postgresql-ca.pem:/certs/postgresql-ca.pem:ro
    networks:
      - mulo-shared-net

networks:
  mulo-shared-net:
    external: true
